### PR TITLE
First command macro polish #281

### PR DESCRIPTION
**Pull request by toyboot4e**
PR for #281. If it looks right, I can change all the files using `define_node_command!` to use `define_swap_command!`.

`light.rs` will be:

```rust
define_swap_command! {
    Node::as_light_mut,
    SetLightScatterCommand(Vector3<f32>): scatter, set_scatter, "Set Light Scatter";
    SetLightScatterEnabledCommand(bool): is_scatter_enabled, enable_scatter, "Set Light Scatter Enabled";
    SetLightIntensityCommand(f32): intensity, set_intensity, "Set Light Intensity";
    SetLightCastShadowsCommand(bool): is_cast_shadows, set_cast_shadows, "Set Light Cast Shadows";
    SetLightColorCommand(Color): color, set_color, "Set Light Color";
}

fn node_as_spot_mut(node: &mut Node) -> &mut SpotLight {
    node.as_light_mut().as_spot_mut()
}

define_swap_command! {
    node_as_spot_mut,
    SetSpotLightHotspotCommand(Vector3<f32>): scatter, set_scatter, "Set Spot Light Hotswap";
    SetPointLightShadowBiasCommand(f32): shadow_bias, set_shadow_bias, "Set Point Light Shadow Bias";
    SetSpotLightFalloffAngleDeltaCommand(f32): falloff_angle_delta, set_falloff_angle_delta, "Set Spot Light Falloff Angle Delta";
    SetSpotLightShadowBiasCommand(f32): shadow_bias, set_shadow_bias, "Set Spot Light Shadow Bias";
    SetSpotLightDistanceCommand(f32): distance, set_distance, "Set Spot Light Distance";
    SetSpotLightCookieTextureCommand(Option<Texture>): cookie_texture, set_cookie_texture, "Set Spot Light Cookie Texture";
}

fn node_as_point_light_mut(node: &mut Node) -> &mut PointLight {
    node.as_light_mut().as_point_mut()
}

define_swap_command! {
    node_as_point_light_mut,
    SetPointLightRadiusCommand(f32): radius, set_radius, "Set Point Light Radius";
}
```

### CODE REVIEW

**Comment by mrDIMAS** [comment]
Awesome! It looks much more compact, great job! If you have some spare time to change all files with `define_node_command`, that would be great. However please do not delete `define_node_command` yet, this PR (https://github.com/FyroxEngine/Fyrox/pull/280) still uses it.

**Comment by toyboot4e** [comment]
This PR tries to improve scene command macro call syntax.

1. By adding `define_swap_command!` (not a good name!), an alternative to `define_node_command!` (see above).
2. By changing `define_node_command!` to take multiple command syntax:

```rust
define_node_command! {
    SetPostRotationCommand("Set Post Rotation", UnitQuaternion<f32>) where fn swap(self, node) {
        let temp = **node.local_transform().post_rotation();
        node.local_transform_mut().set_post_rotation(self.value);
        self.value = temp;
    }

    SetPreRotationCommand("Set Pre Rotation", UnitQuaternion<f32>) where fn swap(self, node) {
        let temp = **node.local_transform().pre_rotation();
        node.local_transform_mut().set_pre_rotation(self.value);
        self.value = temp;
    }
    /* ~~~~ */
}
```

Next step after this PR (if we take) would be to separate `define_swap_command!`:

* One for `structP definition
* Another for `Command` implementation

..so that custom `define_*_command!` can be easily defined in sub modules.

**Comment by mrDIMAS** [comment]
Great job, thank you! Could you please post an example of further improvements?

**Comment by toyboot4e** [comment]
Sure! I'm considering the followings..

# Core macros in shorte lines

## Before

```rust
macro_rules! define_emitter_command {
    // core impl
    ($(#[$meta:meta])* $type:ident($value_type:ty): $name:expr, $swap:expr) => {
        $(#[$meta])*
        #[derive(Debug)]
        pub struct $type {
            handle: $crate::fyrox::core::pool::Handle<Node>,
            index: usize,
            value: $value_type,
        }

        impl $type {
            pub fn new(handle: $crate::fyrox::core::pool::Handle<Node>, index: usize, value: $value_type) -> Self {
                Self { handle, index, value }
            }

            fn swap(&mut self, graph: &mut $crate::fyrox::scene::graph::Graph) {
                let emitter = &mut graph[self.handle].as_particle_system_mut().emitters[self.index];
                #[allow(clippy::redundant_closure_call)]
                ($swap)(self, emitter)
            }
        }

        impl Command for $type {
            fn name(&mut self, _context: &SceneContext) -> String {
                $name.to_owned()
            }

            fn execute(&mut self, context: &mut SceneContext) {
                self.swap(&mut context.scene.graph);
            }

            fn revert(&mut self, context: &mut SceneContext) {
                self.swap(&mut context.scene.graph);
            }
        }
    };

    /* ~~~~ */
}
```

## After

```rust
macro_rules! define_emitter_command {
    // core impl
    ($(#[$meta:meta])* $type:ident($value_type:ty): $name:expr, $swap:expr) => {
        define_command_struct! {
            handle: Handle<Node>,
            index: usize,
            value: $value_type,
        }

        impl_swap_command! {
            $type: $name, fn swap(&mut self, graph: &mut Graph) {
                let emitter = &mut graph[self.handle].as_particle_system_mut().emitters[self.index];
                #[allow(clippy::redundant_closure_call)]
                ($swap)(self, emitter)
            }
        }
    };
}
```

# Driving macros in shorter lines

## Before

```rust
macro_rules! define_emitter_variant_command {
    ($( $(#[$meta:meta])* $ty_name:ident($value_type:ty): $variant:ident, $get:ident, $set:ident, $name_expr:expr;)*) => {
        $(
            define_emitter_command! {
                $(#[$meta:meta])*
                $ty_name($value_type): $name_expr, |me: &mut Self, emitter: &mut Emitter| {
                    let variant = match emitter {
                        Emitter::$variant(x) => x,
                        _ => unreachable!(),
                    };
                    let old = variant.$get();
                    let _ = variant.$set(me.value.clone());
                    me.value = old;
                }
            }
        )*
    };
}
```

## After

```rust
macro_rules! define_emitter_variant_command {
    ($(xs:tt)*) => {
        $(
            impl_variant_command! {
                define_emitter_command,
                Emitter,
                $(xs)*
            }
        )*
    }
}
```

**Comment by mrDIMAS** [comment]
Cool! You can experiment freely here, I want to get rid of most of boilerplate code.

**Pull request merged**
